"""Human-curated conversational pools for natural-feeling responses.

This module contains manually crafted response variants organized by emotional state
and conversational category. The orchestration layer dynamically assembles responses
from these pools while maintaining repetition suppression and behavioral continuity.

Design principles:
* Human conversational tone, not robotic therapist formatting
* State-specific vocabulary to avoid semantic anchor repetition
* Natural paragraph flow with minimal bullet points
* 30-35 variants per category for sufficient diversity
"""

import random
from typing import Dict, List, Optional


# ============================================
# ANXIETY POOLS
# ============================================

ANXIETY_INTROS = [
    "I can help with that.",
    "That sounds really difficult.",
    "I'm here to support you through this.",
    "Let's work through this together.",
    "That sounds overwhelming.",
    "I understand how challenging that feels.",
    "You're not alone in feeling this way.",
    "That sounds like a lot to handle.",
    "I'm here to listen and help.",
    "That sounds really stressful.",
    "I can see why this is affecting you.",
    "That sounds exhausting.",
    "I'm here to help you find some relief.",
    "That sounds like it's taking a toll.",
    "I understand how overwhelming that can feel.",
    "I'm here to support you.",
    "That sounds like it's weighing on you.",
    "I can help you work through this.",
    "That sounds really challenging.",
    "I'm here to help you navigate this.",
    "That sounds like it's creating a lot of pressure.",
    "I understand how difficult this must be.",
    "I'm here to help you find balance.",
    "That sounds like it's affecting your daily life.",
    "I can help you manage this stress.",
    "That sounds really intense.",
    "I'm here to help you find some calm.",
    "That sounds like it's disrupting your peace.",
    "I understand how that can feel consuming.",
    "I'm here to help you regain control.",
    "That sounds like it's creating constant tension.",
    "I can help you find relief from this.",
    "That sounds like it's impacting your wellbeing.",
    "I'm here to help you through this challenge.",
    "That sounds like it's causing significant distress.",
]

ANXIETY_OBSERVATIONS = [
    "Your responses suggest signs of anxiety-driven cognitive tension.",
    "It sounds like your mind is racing with persistent thoughts.",
    "Your description indicates heightened mental alertness.",
    "It seems like you're experiencing mental restlessness.",
    "Your words suggest ongoing cognitive overload.",
    "It sounds like you're dealing with persistent mental tension.",
    "Your responses indicate heightened uncertainty loops.",
    "It seems like you're experiencing hypervigilant thinking patterns.",
    "Your description suggests ongoing mental agitation.",
    "It sounds like you're dealing with racing thoughts.",
    "Your responses indicate cognitive hyperactivity.",
    "It seems like you're experiencing constant mental tension.",
    "Your words suggest persistent mental stimulation.",
    "It sounds like you're dealing with heightened mental arousal.",
    "Your responses indicate ongoing cognitive strain.",
    "It seems like you're experiencing mental restlessness.",
    "Your description suggests persistent mental activation.",
    "It sounds like you're dealing with cognitive tension.",
    "Your responses indicate heightened mental energy.",
    "It seems like you're experiencing ongoing mental stimulation.",
    "Your words suggest persistent cognitive arousal.",
    "It sounds like you're dealing with mental hyperactivity.",
    "Your responses indicate ongoing mental tension.",
    "It seems like you're experiencing heightened cognitive activity.",
    "Your description suggests persistent mental stimulation.",
    "It sounds like you're dealing with cognitive restlessness.",
    "Your responses indicate ongoing mental arousal.",
    "It seems like you're experiencing heightened mental tension.",
    "Your words suggest persistent cognitive hyperactivity.",
    "It sounds like you're dealing with ongoing mental stimulation.",
    "Your responses indicate cognitive agitation.",
    "It seems like you're experiencing persistent mental tension.",
    "Your description suggests heightened mental activity.",
    "It sounds like you're dealing with cognitive restlessness.",
    "Your responses indicate ongoing mental hyperactivity.",
    "It seems like you're experiencing persistent mental tension.",
]

ANXIETY_REASONING = [
    "When the mind stays in this activated state, it can be difficult to find moments of genuine calm.",
    "This kind of cognitive tension often creates a cycle where thoughts feed on each other.",
    "The nervous system can become conditioned to stay in this heightened state of alertness.",
    "Mental restlessness tends to amplify itself through repeated thought patterns.",
    "When cognitive overload persists, it can affect your ability to fully relax.",
    "This type of mental tension often makes it harder to find mental clarity.",
    "The mind can get stuck in loops of persistent stimulation and tension.",
    "When cognitive hyperactivity continues, it can impact your overall sense of peace.",
    "This kind of mental agitation often creates difficulty finding moments of stillness.",
    "The nervous system can become overstimulated and struggle to return to baseline.",
    "When mental tension persists, it can affect your ability to concentrate fully.",
    "This type of cognitive arousal often makes relaxation feel more difficult.",
    "The mind can become conditioned to maintain this heightened level of activity.",
    "When cognitive stimulation continues, it can impact your emotional wellbeing.",
    "This kind of mental restlessness often creates challenges finding inner calm.",
    "The nervous system can struggle to regulate when constantly activated.",
    "When mental hyperactivity persists, it can affect your daily functioning.",
    "This type of cognitive tension often makes it harder to find balance.",
    "The mind can get caught in cycles of persistent mental activation.",
    "When cognitive arousal continues, it can impact your sleep quality.",
    "This kind of mental agitation often creates difficulty with relaxation.",
    "The nervous system can become conditioned to stay in this alert state.",
    "When mental tension persists, it can affect your ability to focus.",
    "This type of cognitive hyperactivity often makes stillness feel elusive.",
    "The mind can struggle to find peace when constantly stimulated.",
    "When cognitive stimulation continues, it can impact your emotional regulation.",
    "This kind of mental restlessness often creates challenges with concentration.",
    "The nervous system can become overactive and struggle to calm down.",
    "When mental hyperactivity persists, it can affect your overall wellbeing.",
    "This type of cognitive tension often makes relaxation feel difficult.",
    "The mind can get stuck in patterns of persistent activation.",
    "When cognitive arousal continues, it can impact your daily life.",
    "This kind of mental agitation often creates difficulty finding calm.",
    "The nervous system can struggle to regulate when constantly aroused.",
]

ANXIETY_INTERVENTIONS = [
    "Right now, focusing on reducing mental stimulation might help more than trying to force productivity. Consider setting aside specific times for deep breathing exercises and creating quiet moments without screens.",
    "It might help to establish small boundaries around mental stimulation. Try scheduling brief periods where you step away from constant input and allow your mind to rest.",
    "Creating structured mental breaks could provide some relief. Consider setting specific times during the day for short mindfulness practices or simply sitting in quiet reflection.",
    "When thoughts feel overwhelming, it can help to have a grounding technique ready. Try focusing on your breathing or engaging in a simple physical activity to redirect mental energy.",
    "Building a routine that includes moments of mental stillness might help. Consider starting with just five minutes of quiet time each day and gradually increasing as it feels comfortable.",
    "It might be beneficial to create some mental space by reducing unnecessary stimulation. Try identifying one source of constant input you can temporarily limit.",
    "When cognitive tension feels high, physical movement can help redirect energy. Consider gentle stretching or walking to help regulate your nervous system.",
    "Creating a calming evening routine might help with mental restlessness. Try avoiding stimulating content before bed and replacing it with relaxing activities.",
    "It could help to practice observing your thoughts without getting caught up in them. Try imagining thoughts as clouds passing by rather than engaging with each one.",
    "Building in moments of sensory focus might provide grounding. Try paying attention to specific sounds, textures, or sights to redirect mental energy.",
    "When mental hyperactivity persists, it might help to have a structured wind-down routine. Consider creating consistent evening rituals that signal relaxation to your nervous system.",
    "It could be beneficial to practice progressive muscle relaxation when tension feels high. Try systematically tensing and releasing different muscle groups.",
    "Creating mental boundaries around work or study might help. Try setting clear end times and creating transition rituals to signal completion.",
    "When thoughts race, it might help to have a worry scheduling technique. Try setting aside specific times to process concerns rather than letting them interrupt constantly.",
    "Building in regular physical activity could help regulate mental energy. Consider activities that engage both body and mind like yoga or tai chi.",
    "It might help to create a mental sanctuary space. Try identifying a place or activity that consistently brings you calm and make it accessible.",
    "When cognitive tension feels overwhelming, journaling might help process thoughts. Try writing without judgment to externalize mental activity.",
    "Creating structured social time might help with mental restlessness. Try planning meaningful interactions that provide genuine connection.",
    "It could help to practice the 5-4-3-2-1 grounding technique. Try identifying five things you see, four you touch, three you hear, two you smell, one you taste.",
    "Building in creative outlets might redirect mental energy. Try activities that engage your focus in a flowing, absorbing way.",
    "When mental hyperactivity persists, it might help to have a calming mantra. Try repeating a phrase that brings you comfort and focus.",
    "Creating mental boundaries around information consumption might help. Try limiting exposure to news and social media at specific times.",
    "It could help to practice body scan meditation when tension feels high. Try systematically bringing awareness to different parts of your body.",
    "Building in nature exposure might help regulate mental energy. Try spending time outdoors or bringing natural elements into your environment.",
    "When cognitive tension feels overwhelming, talking with someone might help. Try sharing your thoughts with a trusted friend or family member.",
    "Creating a calming morning routine might help start the day with less mental tension. Try beginning with gentle movement or quiet reflection.",
    "It might help to practice cognitive defusion techniques. Try observing thoughts as mental events rather than absolute truths.",
    "Building in regular sleep hygiene might help with mental restlessness. Try maintaining consistent sleep and wake times.",
    "When mental hyperactivity persists, it could help to have a structured relaxation practice. Try setting aside specific times for calming activities.",
    "Creating mental boundaries around decision-making might help. Try limiting the number of choices you need to make in a day.",
    "It could help to practice visualization techniques when tension feels high. Try imagining a peaceful place or situation.",
    "Building in regular social connection might help regulate mental energy. Try scheduling consistent meaningful interactions.",
    "When cognitive tension feels overwhelming, professional support might be beneficial. Consider speaking with a mental health provider.",
    "Creating a calming sensory environment might help. Try adjusting lighting, sounds, and textures to promote relaxation.",
]

ANXIETY_FOLLOWUPS = [
    "Do your thoughts feel more overwhelming at night or during work/study situations?",
    "When do you notice the mental tension feeling strongest?",
    "What tends to trigger the racing thoughts for you?",
    "Have you noticed any patterns in when you feel most mentally restless?",
    "How long have you been feeling this level of cognitive tension?",
    "Does the mental hyperactivity feel worse in specific environments?",
    "What situations tend to amplify the mental stimulation for you?",
    "Have you noticed times when your mind feels calmer?",
    "Does the cognitive tension affect your sleep patterns?",
    "What helps you find even small moments of mental relief?",
    "Have you noticed any physical sensations that accompany the mental tension?",
    "Does the mental restlessness impact your ability to concentrate?",
    "What time of day do the thoughts feel most intense?",
    "Have you tried any techniques that help with the mental agitation?",
    "Does the cognitive hyperactivity affect your appetite or energy?",
    "What environments tend to make the mental tension worse?",
    "Have you noticed any changes in your sleep when tension is high?",
    "Does the mental stimulation feel more internal or externally triggered?",
    "What activities help you find even brief moments of calm?",
    "Have you noticed any patterns in what triggers the cognitive tension?",
    "Does the mental restlessness affect your relationships with others?",
    "What helps you redirect your mental energy when it feels overwhelming?",
    "Have you noticed any physical symptoms that accompany the tension?",
    "Does the cognitive hyperactivity impact your daily functioning?",
    "What times of day do you feel most mentally activated?",
    "Have you tried any relaxation techniques that help?",
    "Does the mental tension affect your ability to enjoy activities?",
    "What environments tend to make the mental stimulation worse?",
    "Have you noticed any changes in your appetite or sleep?",
    "Does the mental restlessness feel worse when you're alone or with others?",
    "What helps you find even small moments of relief from the tension?",
    "Have you noticed any patterns in what amplifies the cognitive tension?",
    "Does the mental hyperactivity affect your concentration or focus?",
    "What activities help you regulate your mental energy?",
    "Have you noticed any physical sensations that come with the tension?",
    "Does the mental stimulation feel more constant or episodic?",
    "What helps you find moments of calm when thoughts race?",
]


# ============================================
# DEPRESSION POOLS
# ============================================

DEPRESSION_INTROS = [
    "I'm here with you.",
    "That sounds really heavy.",
    "I understand how difficult this feels.",
    "You're not alone in this.",
    "That sounds emotionally exhausting.",
    "I'm here to support you.",
    "That sounds like a heavy burden.",
    "I understand how draining that can be.",
    "I'm here to help you through this.",
    "That sounds like it's weighing on you.",
    "You don't have to carry this alone.",
    "That sounds emotionally taxing.",
    "I understand how exhausting that must be.",
    "I'm here to listen and help.",
    "That sounds like it's taking a lot out of you.",
    "You deserve support through this.",
    "That sounds emotionally demanding.",
    "I understand how heavy that feels.",
    "I'm here to help you find some relief.",
    "That sounds like it's depleting your energy.",
    "You don't have to face this by yourself.",
    "That sounds emotionally overwhelming.",
    "I understand how taxing that can be.",
    "I'm here to help you navigate this.",
    "That sounds like it's draining your reserves.",
    "You deserve care and support.",
    "That sounds emotionally burdensome.",
    "I understand how exhausting that must feel.",
    "I'm here to help you through this challenge.",
    "That sounds like it's consuming your energy.",
    "You don't have to carry this burden alone.",
    "That sounds emotionally depleting.",
    "I understand how heavy that must be.",
    "I'm here to support you through this.",
    "That sounds like it's taking a toll on you.",
    "You deserve compassion and support.",
]

DEPRESSION_OBSERVATIONS = [
    "Your responses suggest signs of emotional heaviness and motivational depletion.",
    "It sounds like you're experiencing significant emotional fatigue.",
    "Your description indicates low emotional energy and disconnection.",
    "It seems like you're dealing with emotional numbness.",
    "Your words suggest persistent motivational depletion.",
    "It sounds like you're experiencing emotional exhaustion.",
    "Your responses indicate emotional heaviness that affects daily life.",
    "It seems like you're dealing with low emotional vitality.",
    "Your description suggests emotional disconnection from activities.",
    "It sounds like you're experiencing motivational fatigue.",
    "Your responses indicate emotional depletion.",
    "It seems like you're dealing with emotional heaviness.",
    "Your words suggest low emotional energy.",
    "It sounds like you're experiencing emotional numbness.",
    "Your responses indicate motivational depletion.",
    "It seems like you're dealing with emotional exhaustion.",
    "Your description suggests emotional fatigue.",
    "It sounds like you're experiencing emotional heaviness.",
    "Your responses indicate low emotional vitality.",
    "It seems like you're dealing with emotional disconnection.",
    "Your words suggest motivational fatigue.",
    "It sounds like you're experiencing emotional depletion.",
    "Your responses indicate emotional numbness.",
    "It seems like you're dealing with motivational depletion.",
    "Your description suggests emotional heaviness.",
    "It sounds like you're experiencing emotional exhaustion.",
    "Your responses indicate emotional fatigue.",
    "It seems like you're dealing with low emotional energy.",
    "Your words suggest emotional disconnection.",
    "It sounds like you're experiencing motivational depletion.",
    "Your responses indicate emotional heaviness.",
    "It seems like you're dealing with emotional exhaustion.",
    "Your description suggests emotional depletion.",
    "It sounds like you're experiencing emotional numbness.",
    "Your responses indicate low emotional vitality.",
    "It seems like you're dealing with motivational fatigue.",
    "Your words suggest emotional heaviness.",
    "It sounds like you're experiencing emotional exhaustion.",
]

DEPRESSION_REASONING = [
    "When emotional energy feels this depleted, even simple tasks can require significant effort.",
    "This kind of emotional heaviness often makes it difficult to find motivation for activities that once brought joy.",
    "The emotional system can become conditioned to conserve energy when experiencing persistent depletion.",
    "Motivational fatigue tends to affect your ability to engage with daily responsibilities.",
    "When emotional numbness persists, it can impact your connection with yourself and others.",
    "This type of emotional exhaustion often makes it harder to find pleasure in usual activities.",
    "The emotional system can struggle to regulate when experiencing persistent heaviness.",
    "When motivational depletion continues, it can affect your sense of purpose and direction.",
    "This kind of emotional disconnection often creates challenges with social engagement.",
    "The emotional system can become overwhelmed and struggle to maintain positive affect.",
    "When emotional fatigue persists, it can impact your ability to care for yourself properly.",
    "This type of emotional heaviness often makes concentration and decision-making difficult.",
    "The emotional system can struggle to find balance when experiencing persistent depletion.",
    "When motivational fatigue continues, it can affect your sleep patterns and appetite.",
    "This kind of emotional numbness often creates difficulty experiencing positive emotions.",
    "The emotional system can become conditioned to expect low energy states.",
    "When emotional exhaustion persists, it can impact your physical wellbeing.",
    "This type of emotional heaviness often makes social interactions feel draining.",
    "The emotional system can struggle to maintain motivation when constantly depleted.",
    "When motivational depletion continues, it can affect your sense of self-worth.",
    "This kind of emotional fatigue often creates challenges with problem-solving.",
    "The emotional system can become overwhelmed and struggle to regulate effectively.",
    "When emotional numbness persists, it can impact your ability to connect with others.",
    "This type of emotional heaviness often makes it difficult to find meaning in activities.",
    "The emotional system can struggle to maintain energy when constantly fatigued.",
    "When motivational fatigue continues, it can affect your daily functioning.",
    "This kind of emotional exhaustion often creates difficulty with self-care.",
    "The emotional system can become conditioned to expect low engagement.",
    "When emotional depletion persists, it can impact your relationships.",
    "This type of emotional heaviness often makes concentration challenging.",
    "The emotional system can struggle to find pleasure when constantly exhausted.",
    "When motivational fatigue continues, it can affect your sense of hope.",
    "This kind of emotional numbness often creates challenges with emotional expression.",
    "The emotional system can become overwhelmed and struggle to maintain balance.",
]

DEPRESSION_INTERVENTIONS = [
    "Right now, rebuilding momentum gradually might help more than forcing high productivity. Consider starting with very small, achievable tasks and celebrating each completion.",
    "It might help to focus on restoring basic routines first. Try establishing consistent sleep and wake times, even if other activities feel difficult.",
    "Creating structure around self-care could provide some stability. Consider scheduling basic activities like meals and hygiene at regular times.",
    "When emotional energy feels depleted, gentle movement might help. Try short walks or gentle stretching without pressure to achieve specific outcomes.",
    "Building in small social connections might help with emotional disconnection. Try brief interactions with trusted friends or family members.",
    "It could help to practice self-compassion when motivation feels low. Try treating yourself with the same kindness you would offer a friend.",
    "Creating moments of sensory engagement might help with emotional numbness. Try paying attention to pleasant textures, sounds, or tastes.",
    "When emotional heaviness feels overwhelming, breaking tasks into smaller steps might help. Try focusing on just one small action at a time.",
    "Building in gentle creative activities might help with emotional fatigue. Try simple creative outlets without judgment about quality.",
    "It could help to practice gratitude when emotional energy feels depleted. Try noticing one small positive thing each day.",
    "Creating structure around meaningful activities might help with motivational depletion. Try identifying one activity that used to bring joy and attempting it briefly.",
    "When emotional numbness persists, it might help to have a routine that includes pleasant experiences. Try scheduling small enjoyable activities.",
    "Building in regular self-care practices might help with emotional exhaustion. Try basic activities like bathing or changing clothes regularly.",
    "It could help to practice mindfulness when emotional heaviness feels overwhelming. Try observing thoughts without judgment.",
    "Creating social support structures might help with emotional disconnection. Try reaching out to one trusted person regularly.",
    "When motivational fatigue continues, it might help to have a routine that includes accomplishment. Try setting very small daily goals.",
    "Building in nature exposure might help with emotional depletion. Try spending time outdoors or bringing natural elements into your space.",
    "It could help to practice journaling when emotional numbness feels persistent. Try writing without pressure to be positive.",
    "Creating structure around nutrition might help with emotional exhaustion. Try regular meals even if appetite is low.",
    "When emotional heaviness feels overwhelming, professional support might be beneficial. Consider speaking with a mental health provider.",
    "Building in gentle physical activity might help with motivational depletion. Try movement that feels accessible and not demanding.",
    "It could help to practice self-validation when emotional energy feels low. Try acknowledging the difficulty of your experience.",
    "Creating moments of accomplishment might help with emotional fatigue. Try completing one small task each day.",
    "Building in social connection might help with emotional disconnection. Try scheduling regular contact with supportive people.",
    "When emotional numbness persists, it might help to have a routine that includes emotional expression. Try listening to music or watching films.",
    "It could help to practice gentle self-care when emotional heaviness feels overwhelming. Try basic activities like skin care or comfortable clothing.",
    "Creating structure around sleep might help with emotional exhaustion. Try maintaining consistent sleep routines.",
    "When motivational fatigue continues, professional support might be beneficial. Consider therapy or counseling.",
    "Building in meaningful activities might help with emotional depletion. Try engaging in activities that align with your values.",
    "It could help to practice self-acceptance when emotional numbness feels persistent. Try allowing emotions to be present without judgment.",
    "Creating social support might help with emotional disconnection. Try joining support groups or community activities.",
    "When emotional heaviness feels overwhelming, it might help to have a crisis plan. Try identifying emergency resources.",
]

DEPRESSION_FOLLOWUPS = [
    "Have you also noticed losing interest in things you normally enjoy?",
    "How long have you been feeling this emotional heaviness?",
    "Does the emotional exhaustion affect your sleep patterns?",
    "Have you noticed any changes in your appetite or energy levels?",
    "What activities used to bring you joy that now feel difficult?",
    "Does the emotional disconnection affect your relationships with others?",
    "Have you noticed any physical symptoms that accompany the emotional fatigue?",
    "What helps you find even small moments of relief from the heaviness?",
    "Does the motivational depletion impact your ability to care for yourself?",
    "Have you noticed any patterns in when the emotional numbness feels stronger?",
    "What environments tend to make the emotional exhaustion worse?",
    "Have you tried any techniques that help with the emotional heaviness?",
    "Does the emotional fatigue affect your concentration or decision-making?",
    "What helps you find even brief moments of emotional relief?",
    "Have you noticed any changes in your social interactions?",
    "Does the motivational depletion impact your daily functioning?",
    "What times of day do you feel most emotionally exhausted?",
    "Have you noticed any physical sensations that come with the emotional fatigue?",
    "Does the emotional numbness affect your ability to experience positive emotions?",
    "What activities help you find even small moments of connection?",
    "Have you noticed any patterns in what triggers the emotional heaviness?",
    "Does the emotional exhaustion affect your sleep quality?",
    "What helps you find even brief moments of motivation?",
    "Have you noticed any changes in your appetite or weight?",
    "Does the motivational depletion impact your relationships?",
    "What environments tend to make the emotional disconnection worse?",
    "Have you tried any self-care practices that help?",
    "Does the emotional fatigue affect your ability to concentrate?",
    "What helps you find even small moments of pleasure?",
    "Have you noticed any patterns in when the emotional heaviness feels worse?",
    "Does the emotional numbness affect your connection with others?",
    "What helps you find even brief moments of relief?",
    "Have you noticed any physical symptoms that accompany the emotional exhaustion?",
    "Does the emotional fatigue impact your daily activities?",
    "What helps you find even small moments of energy?",
    "Have you noticed any changes in your sleep patterns?",
    "Does the motivational depletion affect your sense of purpose?",
    "What helps you find even brief moments of joy?",
]


# ============================================
# BURNOUT POOLS
# ============================================

BURNOUT_INTROS = [
    "What you're describing sounds closer to sustained burnout than temporary tiredness.",
    "That sounds like you're running on empty.",
    "I understand how exhausting that must feel.",
    "That sounds like prolonged depletion.",
    "You're experiencing significant emotional and mental fatigue.",
    "That sounds like it's been building for some time.",
    "I understand how draining prolonged exhaustion can be.",
    "That sounds like it's affecting every part of your life.",
    "You're dealing with significant depletion.",
    "That sounds like it's been accumulating over time.",
    "I understand how overwhelming sustained exhaustion feels.",
    "That sounds like it's taking a serious toll.",
    "You're experiencing profound fatigue.",
    "That sounds like it's been building gradually.",
    "I understand how taxing prolonged burnout can be.",
    "That sounds like it's impacting your wellbeing significantly.",
    "You're dealing with sustained exhaustion.",
    "That sounds like it's been developing over time.",
    "I understand how draining chronic fatigue can feel.",
    "That sounds like it's affecting your daily functioning.",
    "You're experiencing significant burnout.",
    "That sounds like it's been accumulating gradually.",
    "I understand how overwhelming prolonged depletion feels.",
    "That sounds like it's taking a major toll.",
    "You're dealing with profound exhaustion.",
    "That sounds like it's been building over time.",
    "I understand how taxing chronic burnout can be.",
    "That sounds like it's impacting your quality of life.",
    "You're experiencing sustained fatigue.",
    "That sounds like it's been developing gradually.",
    "I understand how draining prolonged exhaustion can feel.",
    "That sounds like it's affecting your ability to function.",
    "You're dealing with significant burnout.",
    "That sounds like it's been accumulating over time.",
    "I understand how overwhelming chronic fatigue can feel.",
]

BURNOUT_OBSERVATIONS = [
    "Your responses suggest signs of sustained exhaustion and recovery deficit.",
    "It sounds like you're experiencing prolonged emotional and mental fatigue.",
    "Your description indicates significant depletion that affects daily functioning.",
    "It seems like you're dealing with chronic overload that hasn't been resolved.",
    "Your words suggest persistent emotional fatigue that impacts wellbeing.",
    "It sounds like you're experiencing sustained mental and physical exhaustion.",
    "Your responses indicate significant burnout that affects multiple life areas.",
    "It seems like you're dealing with prolonged depletion without adequate recovery.",
    "Your description suggests chronic fatigue that impacts daily activities.",
    "It sounds like you're experiencing sustained emotional and cognitive exhaustion.",
    "Your responses indicate significant burnout that affects your ability to function.",
    "It seems like you're dealing with prolonged overload without sufficient rest.",
    "Your words suggest persistent fatigue that impacts your quality of life.",
    "It sounds like you're experiencing sustained mental and emotional exhaustion.",
    "Your responses indicate significant burnout that affects your wellbeing.",
    "It seems like you're dealing with chronic depletion without recovery.",
    "Your description suggests prolonged fatigue that impacts daily functioning.",
    "It sounds like you're experiencing sustained emotional and physical exhaustion.",
    "Your responses indicate significant burnout that affects multiple areas.",
    "It seems like you're dealing with prolonged overload without rest.",
    "Your words suggest persistent fatigue that impacts your ability to cope.",
    "It sounds like you're experiencing sustained mental and emotional exhaustion.",
    "Your responses indicate significant burnout that affects your daily life.",
    "It seems like you're dealing with chronic depletion without adequate recovery.",
    "Your description suggests prolonged fatigue that impacts your functioning.",
    "It sounds like you're experiencing sustained emotional and cognitive exhaustion.",
    "Your responses indicate significant burnout that affects your wellbeing.",
    "It seems like you're dealing with prolonged overload without sufficient rest.",
    "Your words suggest persistent fatigue that impacts your quality of life.",
    "It sounds like you're experiencing sustained mental and emotional exhaustion.",
    "Your responses indicate significant burnout that affects your ability to function.",
    "It seems like you're dealing with chronic depletion without recovery.",
    "Your description suggests prolonged fatigue that impacts daily activities.",
    "It sounds like you're experiencing sustained emotional and physical exhaustion.",
    "Your responses indicate significant burnout that affects multiple life areas.",
    "It seems like you're dealing with prolonged overload without adequate rest.",
]

BURNOUT_REASONING = [
    "When the system experiences prolonged overload without adequate recovery, it can enter a state of chronic exhaustion.",
    "This kind of sustained fatigue often affects your ability to engage in activities that once felt manageable.",
    "The body and mind can become conditioned to expect constant depletion when experiencing chronic burnout.",
    "Prolonged exhaustion tends to impact your emotional regulation and cognitive functioning.",
    "When recovery deficit persists, it can affect your physical health and immune system functioning.",
    "This type of chronic fatigue often makes it difficult to find motivation for even basic activities.",
    "The nervous system can become dysregulated when experiencing sustained overload and exhaustion.",
    "When burnout continues, it can affect your relationships and social connections.",
    "This kind of prolonged depletion often creates challenges with concentration and memory.",
    "The body can struggle to maintain homeostasis when constantly experiencing exhaustion.",
    "When sustained fatigue persists, it can impact your sense of purpose and meaning.",
    "This type of chronic exhaustion often makes it difficult to experience pleasure or joy.",
    "The mind can become foggy and struggle with decision-making when experiencing prolonged burnout.",
    "When recovery deficit continues, it can affect your sleep patterns and appetite.",
    "This kind of prolonged fatigue often creates physical symptoms like headaches and muscle tension.",
    "The body can struggle to repair and regenerate when constantly experiencing exhaustion.",
    "When sustained burnout persists, it can affect your immune system and overall health.",
    "This type of chronic depletion often makes it difficult to maintain relationships.",
    "The mind can become overwhelmed and struggle with emotional regulation.",
    "When prolonged exhaustion continues, it can affect your ability to work or study effectively.",
    "This kind of chronic fatigue often creates challenges with self-care and basic functioning.",
    "The body can struggle to maintain energy levels when constantly depleted.",
    "When sustained burnout persists, it can affect your mood and emotional stability.",
    "This type of prolonged exhaustion often makes it difficult to find motivation.",
    "The mind can become foggy and struggle with cognitive tasks.",
    "When recovery deficit continues, it can affect your physical health.",
    "This kind of chronic fatigue often creates challenges with daily functioning.",
    "The body can struggle to maintain balance when constantly experiencing exhaustion.",
    "When sustained burnout persists, it can affect your overall quality of life.",
    "This type of prolonged depletion often makes it difficult to enjoy activities.",
    "The mind can become overwhelmed and struggle with emotional regulation.",
    "When prolonged exhaustion continues, it can affect your ability to function.",
]

BURNOUT_INTERVENTIONS = [
    "Right now, protecting what energy you still have and rebuilding slowly should be the priority. Consider setting clear boundaries around work or study commitments and saying no to non-essential obligations.",
    "It might help to create structured recovery time in your schedule. Try blocking out specific periods for rest and treating them as non-negotiable appointments.",
    "Creating boundaries around stimulation could provide some relief. Try reducing screen time, social media, and information overload, especially in the evenings.",
    "When exhaustion feels overwhelming, delegating or postponing tasks might help. Try identifying one responsibility you can temporarily set aside or share with others.",
    "Building in genuine rest activities might help with recovery. Try activities that truly restore energy rather than just distracting from exhaustion.",
    "It could help to practice saying no without guilt when your energy is depleted. Try prioritizing your wellbeing over external expectations.",
    "Creating a recovery-focused environment might help. Try adjusting your physical space to promote rest and relaxation.",
    "When burnout feels severe, professional support might be beneficial. Consider speaking with a healthcare provider about your exhaustion.",
    "Building in gentle movement might help with physical exhaustion. Try activities like walking, stretching, or yoga without pressure to achieve specific outcomes.",
    "It could help to practice radical self-acceptance during recovery. Try allowing yourself to rest without judgment about productivity.",
    "Creating structure around basic self-care might help. Try scheduling meals, sleep, and hygiene at consistent times.",
    "When prolonged exhaustion persists, reducing stimulation might help. Try limiting caffeine, sugar, and other substances that affect energy levels.",
    "Building in social connection might help with emotional exhaustion. Try brief interactions with supportive people who don't drain your energy.",
    "It could help to practice mindfulness when burnout feels overwhelming. Try observing your exhaustion without judgment.",
    "Creating a recovery routine might help with sustained fatigue. Try establishing consistent practices that signal rest to your body and mind.",
    "When burnout affects sleep, establishing sleep hygiene might help. Try creating a calming bedtime routine and consistent sleep schedule.",
    "Building in nature exposure might help with exhaustion. Try spending time outdoors or bringing natural elements into your environment.",
    "It could help to practice self-compassion when recovery feels slow. Try treating yourself with kindness during the healing process.",
    "Creating boundaries around emotional labor might help. Try limiting interactions that drain your emotional energy.",
    "When prolonged exhaustion persists, medical evaluation might be appropriate. Consider checking for underlying health conditions.",
    "Building in creative outlets might help with recovery. Try gentle creative activities that don't pressure you to produce.",
    "It could help to practice acceptance when burnout feels severe. Try acknowledging that recovery takes time and patience.",
    "Creating structure around meaningful activities might help. Try identifying small activities that align with your values.",
    "When exhaustion affects concentration, simplifying tasks might help. Try breaking activities into smaller, manageable steps.",
    "Building in sensory pleasure might help with recovery. Try engaging senses through music, aromatherapy, or comfortable textures.",
    "It could help to practice setting realistic expectations during recovery. Try adjusting your standards for productivity and achievement.",
    "Creating a support system might help with burnout. Try identifying people who can provide practical and emotional support.",
    "When prolonged exhaustion persists, gradual return to activities might help. Try slowly reintroducing activities as energy allows.",
    "Building in moments of joy might help with recovery. Try scheduling small pleasant activities without pressure.",
    "It could help to practice patience during the healing process. Try allowing yourself time to recover without rushing.",
    "Creating boundaries around work might help with burnout. Try setting clear limits on working hours and availability.",
    "When exhaustion feels overwhelming, professional support might be beneficial. Consider therapy or counseling for burnout.",
]

BURNOUT_FOLLOWUPS = [
    "Have you been feeling emotionally drained for multiple weeks continuously?",
    "When did you first start noticing this level of sustained exhaustion?",
    "What feels most draining about your current situation?",
    "Have you noticed any physical symptoms that accompany the burnout?",
    "Does the exhaustion affect your ability to enjoy activities?",
    "What aspects of your life feel most depleted right now?",
    "Have you noticed any changes in your sleep patterns?",
    "Does the burnout impact your relationships with others?",
    "What environments tend to make the exhaustion worse?",
    "Have you tried any recovery strategies that helped?",
    "Does the sustained fatigue affect your concentration?",
    "What responsibilities feel most overwhelming right now?",
    "Have you noticed any changes in your appetite or energy?",
    "Does the burnout affect your ability to care for yourself?",
    "What times of day do you feel most exhausted?",
    "Have you noticed any patterns in what triggers the burnout?",
    "Does the prolonged exhaustion affect your mood?",
    "What helps you find even small moments of relief?",
    "Have you noticed any physical symptoms that accompany the fatigue?",
    "Does the burnout impact your daily functioning?",
    "What environments tend to make the exhaustion worse?",
    "Have you tried any self-care practices that help?",
    "Does the sustained fatigue affect your sleep quality?",
    "What responsibilities feel most draining right now?",
    "Have you noticed any changes in your social interactions?",
    "Does the burnout affect your ability to work or study?",
    "What helps you find even brief moments of energy?",
    "Have you noticed any patterns in when the exhaustion feels worse?",
    "Does the prolonged fatigue affect your relationships?",
    "What environments tend to make the burnout worse?",
    "Have you tried any recovery techniques that helped?",
    "Does the sustained exhaustion affect your concentration?",
    "What responsibilities feel most overwhelming right now?",
    "Have you noticed any changes in your physical health?",
    "Does the burnout affect your ability to enjoy life?",
    "What helps you find even small moments of relief?",
]


# ============================================
# DOPAMINE OVERLOAD POOLS
# ============================================

DOPAMINE_INTROS = [
    "I notice patterns that may be linked with overstimulation and reward cycling.",
    "That sounds like your attention is being pulled in many directions.",
    "I understand how difficult it is to focus when constantly stimulated.",
    "That sounds like fragmented attention and reward seeking.",
    "You're dealing with stimulation fatigue and attention fragmentation.",
    "That sounds like it's creating a cycle of constant stimulation.",
    "I understand how challenging it is to maintain focus with so much input.",
    "That sounds like your brain is stuck in reward-seeking loops.",
    "You're experiencing significant attention fragmentation.",
    "That sounds like it's creating constant stimulation cycles.",
    "I understand how exhausting overstimulation can feel.",
    "That sounds like your attention is constantly being redirected.",
    "You're dealing with reward cycling and stimulation fatigue.",
    "That sounds like it's creating difficulty maintaining focus.",
    "I understand how overwhelming constant stimulation can be.",
    "That sounds like your brain is seeking frequent rewards.",
    "You're experiencing significant attention fragmentation.",
    "That sounds like it's creating cycles of stimulation and reward.",
    "I understand how challenging fragmented attention can feel.",
    "That sounds like your focus is constantly being interrupted.",
    "You're dealing with stimulation fatigue and reward seeking.",
    "That sounds like it's creating difficulty concentrating.",
    "I understand how exhausting constant stimulation can be.",
    "That sounds like your attention is being pulled in many directions.",
    "You're experiencing significant reward cycling.",
    "That sounds like it's creating fragmented attention patterns.",
    "I understand how overwhelming overstimulation can feel.",
    "That sounds like your brain is stuck in stimulation loops.",
    "You're dealing with attention fragmentation and reward seeking.",
    "That sounds like it's creating difficulty maintaining focus.",
    "I understand how challenging fragmented attention can be.",
    "That sounds like your focus is constantly being interrupted.",
    "You're experiencing significant stimulation fatigue.",
    "That sounds like it's creating cycles of constant stimulation.",
]

DOPAMINE_OBSERVATIONS = [
    "Your responses suggest signs of overstimulation and fragmented attention patterns.",
    "It sounds like you're experiencing reward cycling that impacts focus.",
    "Your description indicates stimulation fatigue that affects concentration.",
    "It seems like you're dealing with fragmented attention due to constant input.",
    "Your words suggest persistent reward-seeking behavior that disrupts focus.",
    "It sounds like you're experiencing attention fragmentation from overstimulation.",
    "Your responses indicate stimulation fatigue that impacts cognitive performance.",
    "It seems like you're dealing with reward cycling that affects concentration.",
    "Your description suggests fragmented attention patterns.",
    "It sounds like you're experiencing overstimulation that impacts focus.",
    "Your responses indicate reward cycling that affects attention.",
    "It seems like you're dealing with stimulation fatigue that disrupts concentration.",
    "Your words suggest fragmented attention from constant stimulation.",
    "It sounds like you're experiencing reward-seeking behavior that impacts focus.",
    "Your responses indicate overstimulation that affects cognitive performance.",
    "It seems like you're dealing with attention fragmentation due to constant input.",
    "Your description suggests stimulation fatigue that impacts concentration.",
    "It sounds like you're experiencing reward cycling that affects attention.",
    "Your responses indicate fragmented attention patterns.",
    "It seems like you're dealing with overstimulation that disrupts focus.",
    "Your words suggest stimulation fatigue that impacts cognitive performance.",
    "It sounds like you're experiencing attention fragmentation from constant input.",
    "Your responses indicate reward cycling that affects concentration.",
    "It seems like you're dealing with overstimulation that impacts attention.",
    "Your description suggests fragmented attention patterns.",
    "It sounds like you're experiencing stimulation fatigue that disrupts focus.",
    "Your responses indicate reward-seeking behavior that affects cognitive performance.",
    "It seems like you're dealing with attention fragmentation due to constant stimulation.",
    "Your description suggests overstimulation that impacts concentration.",
    "It sounds like you're experiencing reward cycling that affects attention.",
    "Your responses indicate fragmented attention patterns.",
    "It seems like you're dealing with stimulation fatigue that disrupts focus.",
    "Your words suggest overstimulation that impacts cognitive performance.",
    "It sounds like you're experiencing attention fragmentation from constant input.",
    "Your responses indicate reward cycling that affects concentration.",
    "It seems like you're dealing with overstimulation that impacts attention.",
    "Your description suggests fragmented attention patterns.",
]

DOPAMINE_REASONING = [
    "When the brain constantly cycles between stimulation and reward, it can struggle to maintain sustained attention.",
    "This kind of overstimulation often creates difficulty focusing on tasks that don't provide immediate rewards.",
    "The reward system can become conditioned to expect constant stimulation and quick feedback.",
    "Fragmented attention tends to impact your ability to engage in deep, meaningful work.",
    "When stimulation fatigue persists, it can affect your ability to find satisfaction in slower activities.",
    "This type of reward cycling often makes it difficult to complete tasks that require sustained focus.",
    "The brain can become conditioned to seek frequent dopamine hits rather than long-term satisfaction.",
    "When overstimulation continues, it can impact your ability to enjoy quiet, reflective moments.",
    "This kind of fragmented attention often creates challenges with reading, studying, or deep work.",
    "The reward system can struggle to find satisfaction in activities that don't provide immediate stimulation.",
    "When stimulation fatigue persists, it can affect your ability to maintain relationships.",
    "This type of reward cycling often makes it difficult to be present in the moment.",
    "The brain can become conditioned to expect constant novelty and stimulation.",
    "When overstimulation continues, it can impact your sleep quality and relaxation.",
    "This kind of fragmented attention often creates challenges with completing long-term projects.",
    "The reward system can struggle to find satisfaction in everyday activities.",
    "When stimulation fatigue persists, it can affect your emotional regulation.",
    "This type of reward cycling often makes it difficult to enjoy simple pleasures.",
    "The brain can become conditioned to seek constant entertainment and stimulation.",
    "When overstimulation continues, it can impact your ability to concentrate.",
    "This kind of fragmented attention often creates challenges with learning and memory.",
    "The reward system can struggle to find satisfaction in slower-paced activities.",
    "When stimulation fatigue persists, it can affect your relationships.",
    "This type of reward cycling often makes it difficult to be fully present.",
    "The brain can become conditioned to expect constant input and stimulation.",
    "When overstimulation continues, it can impact your ability to relax.",
    "This kind of fragmented attention often creates challenges with productivity.",
    "The reward system can struggle to find satisfaction in routine activities.",
    "When stimulation fatigue persists, it can affect your emotional wellbeing.",
    "This type of reward cycling often makes it difficult to enjoy quiet moments.",
    "The brain can become conditioned to seek constant novelty and entertainment.",
    "When overstimulation continues, it can impact your ability to focus.",
    "This kind of fragmented attention often creates challenges with learning.",
]

DOPAMINE_INTERVENTIONS = [
    "Right now, reducing stimulation intensity might help more than trying to force focus. Try setting specific times for checking notifications and social media rather than constant monitoring.",
    "It might help to create structured stimulation boundaries. Try scheduling device-free periods during the day and especially before bedtime.",
    "Creating deep-focus blocks could provide some relief. Try setting aside specific times for uninterrupted work or study without any digital distractions.",
    "When attention feels fragmented, having a designated distraction zone might help. Try creating a specific area or time for engaging with stimulating content.",
    "Building in stimulation-free activities might help with reward cycling. Try engaging in activities that provide slower, more natural satisfaction like reading or nature walks.",
    "It could help to practice digital minimalism when focus feels difficult. Try reducing the number of apps and notifications that compete for your attention.",
    "Creating a stimulation budget might help with overstimulation. Try allocating specific time limits for engaging with high-stimulation content.",
    "When reward cycling feels intense, having a reward reset might help. Try taking breaks from activities that provide quick dopamine hits.",
    "Building in analog activities might help with fragmented attention. Try engaging with physical books, paper notebooks, or hands-on hobbies.",
    "It could help to practice single-tasking when stimulation feels overwhelming. Try focusing on one activity at a time rather than multitasking.",
    "Creating stimulation-free zones in your environment might help. Try designating specific areas where digital devices aren't allowed.",
    "When attention fragmentation persists, it might help to have a focus ritual. Try creating a consistent routine that signals deep work time.",
    "Building in nature exposure might help with overstimulation. Try spending time outdoors or bringing natural elements into your workspace.",
    "It could help to practice mindful consumption when stimulation feels intense. Try being intentional about what content you engage with.",
    "Creating stimulation boundaries around sleep might help. Try avoiding screens and stimulating content for at least an hour before bedtime.",
    "When reward cycling continues, it might help to have a reward restructuring. Try finding satisfaction in longer-term achievements rather than immediate hits.",
    "Building in analog communication might help with fragmented attention. Try having conversations without digital devices present.",
    "It could help to practice stimulation fasting when focus feels difficult. Try taking regular breaks from all stimulating content.",
    "Creating a focus-friendly environment might help with overstimulation. Try reducing visual and auditory distractions in your workspace.",
    "When attention fragmentation persists, professional support might be beneficial. Consider speaking with a specialist about attention issues.",
    "Building in creative outlets might help with reward cycling. Try engaging in activities that provide flow states and natural satisfaction.",
    "It could help to practice intentional boredom when stimulation feels overwhelming. Try allowing yourself moments without any input or entertainment.",
    "Creating stimulation boundaries around social interactions might help. Try having conversations without checking devices.",
    "When reward cycling continues, it might help to have a satisfaction restructuring. Try finding joy in slower, more meaningful activities.",
    "Building in physical activity might help with fragmented attention. Try exercise that doesn't involve screens or constant stimulation.",
    "It could help to practice digital sunset when stimulation feels intense. Try having a consistent time when all devices are turned off.",
    "Creating stimulation-free morning routines might help with focus. Try starting the day without immediately checking devices or notifications.",
    "When attention fragmentation persists, it might help to have a focus sanctuary. Try creating a specific space dedicated to deep work.",
    "Building in sensory engagement might help with reward cycling. Try activities that engage multiple senses in a natural way.",
    "It could help to practice stimulation awareness when focus feels difficult. Try noticing how different activities affect your attention and energy.",
]

DOPAMINE_FOLLOWUPS = [
    "Do you feel your focus drops quickly after checking social media or short videos?",
    "How often do you find yourself switching between different apps or websites?",
    "Does it feel difficult to stay focused on one task for extended periods?",
    "Do you notice yourself seeking constant stimulation or entertainment?",
    "How does your attention feel after periods of high stimulation?",
    "Do you find it challenging to enjoy activities that don't provide immediate rewards?",
    "How often do you check your phone or notifications throughout the day?",
    "Does it feel difficult to be present without digital stimulation?",
    "Do you notice yourself seeking novelty and new content frequently?",
    "How does your focus feel during device-free periods?",
    "Do you find it challenging to complete longer-term projects?",
    "How often do you engage with short-form content versus longer content?",
    "Does it feel difficult to enjoy quiet, reflective moments?",
    "Do you notice yourself multitasking frequently?",
    "How does your attention feel after reducing stimulation?",
    "Do you find it challenging to read books or longer articles?",
    "How often do you seek out new entertainment or stimulation?",
    "Does it feel difficult to be fully present in conversations?",
    "Do you notice yourself constantly seeking the next dopamine hit?",
    "How does your focus feel when you're not stimulated?",
    "Do you find it challenging to enjoy slow-paced activities?",
    "How often do you switch between different tasks or activities?",
    "Does it feel difficult to complete tasks without immediate rewards?",
    "Do you notice yourself constantly checking for updates or notifications?",
    "How does your attention feel during periods of low stimulation?",
    "Do you find it challenging to engage in deep work?",
    "How often do you seek out new and exciting content?",
    "Does it feel difficult to be present without constant input?",
    "Do you notice yourself frequently switching between apps or websites?",
    "How does your focus feel after reducing digital stimulation?",
    "Do you find it challenging to enjoy activities without immediate gratification?",
    "How often do you engage with stimulating content versus relaxing activities?",
    "Does it feel difficult to maintain focus on one thing?",
    "Do you notice yourself constantly seeking novelty and entertainment?",
    "How does your attention feel during analog activities?",
    "Do you find it challenging to be present without digital distractions?",
]


# ============================================
# PERFORMANCE PRESSURE POOLS
# ============================================

PERFORMANCE_INTROS = [
    "Your responses suggest strong performance pressure and perfectionism patterns.",
    "That sounds like you're dealing with significant achievement pressure.",
    "I understand how exhausting perfectionism can feel.",
    "That sounds like you're experiencing intense self-evaluation.",
    "You're dealing with significant achievement pressure and fear of failure.",
    "That sounds like it's creating constant performance anxiety.",
    "I understand how overwhelming perfectionism can be.",
    "That sounds like you're experiencing intense self-criticism.",
    "You're dealing with significant performance pressure.",
    "That sounds like it's creating constant evaluation anxiety.",
    "I understand how exhausting perfectionism can feel.",
    "That sounds like you're experiencing intense fear of underperforming.",
    "You're dealing with significant achievement pressure.",
    "That sounds like it's creating constant self-evaluation.",
    "I understand how overwhelming perfectionism can be.",
    "That sounds like you're experiencing intense performance anxiety.",
    "You're dealing with significant fear of failure.",
    "That sounds like it's creating constant pressure to achieve.",
    "I understand how exhausting perfectionism can feel.",
    "That sounds like you're experiencing intense self-criticism.",
    "You're dealing with significant performance pressure.",
    "That sounds like it's creating constant evaluation stress.",
    "I understand how overwhelming perfectionism can be.",
    "That sounds like you're experiencing intense achievement anxiety.",
    "You're dealing with significant fear of underperforming.",
    "That sounds like it's creating constant self-evaluation.",
    "I understand how exhausting perfectionism can feel.",
    "That sounds like you're experiencing intense performance pressure.",
    "You're dealing with significant achievement anxiety.",
    "That sounds like it's creating constant perfectionism.",
    "I understand how overwhelming fear of failure can be.",
    "That sounds like you're experiencing intense self-criticism.",
    "You're dealing with significant performance pressure.",
]

PERFORMANCE_OBSERVATIONS = [
    "Your responses suggest signs of perfectionism and fear of failure.",
    "It sounds like you're experiencing intense self-evaluation that impacts performance.",
    "Your description indicates achievement pressure that affects daily functioning.",
    "It seems like you're dealing with perfectionism that creates anxiety.",
    "Your words suggest persistent fear of underperforming that affects wellbeing.",
    "It sounds like you're experiencing performance pressure that impacts motivation.",
    "Your responses indicate perfectionism that affects decision-making.",
    "It seems like you're dealing with achievement pressure that creates stress.",
    "Your description suggests self-criticism patterns.",
    "It sounds like you're experiencing fear of failure that impacts confidence.",
    "Your responses indicate perfectionism that affects relationships.",
    "It seems like you're dealing with performance pressure that affects self-worth.",
    "Your words suggest persistent self-evaluation that creates anxiety.",
    "It sounds like you're experiencing perfectionism that impacts daily life.",
    "Your responses indicate achievement pressure that affects functioning.",
    "It seems like you're dealing with fear of underperforming that affects motivation.",
    "Your description suggests perfectionism patterns.",
    "It sounds like you're experiencing performance pressure that impacts wellbeing.",
    "Your responses indicate self-criticism that affects confidence.",
    "It seems like you're dealing with achievement pressure that affects decisions.",
    "Your words suggest persistent perfectionism that creates stress.",
    "It sounds like you're experiencing fear of failure that impacts self-worth.",
    "Your responses indicate performance pressure that affects relationships.",
    "It seems like you're dealing with perfectionism that affects daily functioning.",
    "Your description suggests self-evaluation patterns.",
    "It sounds like you're experiencing achievement pressure that impacts motivation.",
    "Your responses indicate perfectionism that affects confidence.",
    "It seems like you're dealing with fear of underperforming that affects wellbeing.",
    "Your words suggest persistent performance pressure that creates anxiety.",
    "It sounds like you're experiencing perfectionism that impacts decisions.",
    "Your responses indicate achievement pressure that affects self-worth.",
    "It seems like you're dealing with self-criticism that affects relationships.",
    "Your description suggests perfectionism patterns.",
    "It sounds like you're experiencing performance pressure that impacts functioning.",
    "Your responses indicate fear of underperforming that affects motivation.",
    "It seems like you're dealing with achievement pressure that affects confidence.",
    "Your words suggest persistent perfectionism that creates stress.",
    "It sounds like you're experiencing self-evaluation that impacts self-worth.",
]

PERFORMANCE_REASONING = [
    "When perfectionism becomes the default mode, it can create constant anxiety about performance.",
    "This kind of achievement pressure often makes it difficult to start or complete tasks.",
    "The mind can become conditioned to evaluate every action against impossible standards.",
    "Fear of failure tends to impact your ability to take risks or try new things.",
    "When self-criticism persists, it can affect your self-worth and confidence.",
    "This type of perfectionism often makes it difficult to enjoy achievements.",
    "The mind can get stuck in loops of constant evaluation and self-judgment.",
    "When achievement pressure continues, it can impact your relationships with others.",
    "This kind of fear of failure often creates procrastination and avoidance.",
    "The mind can become conditioned to expect constant evaluation from others.",
    "When perfectionism persists, it can affect your ability to learn from mistakes.",
    "This type of achievement pressure often makes it difficult to ask for help.",
    "The mind can struggle to find satisfaction in accomplishments when standards are too high.",
    "When self-criticism continues, it can affect your mental and physical health.",
    "This kind of perfectionism often creates difficulty with decision-making.",
    "The mind can become overwhelmed by constant pressure to perform.",
    "When achievement pressure persists, it can affect your ability to enjoy life.",
    "This type of fear of failure often makes it difficult to be authentic.",
    "The mind can get stuck in patterns of constant self-evaluation.",
    "When perfectionism continues, it can affect your ability to collaborate.",
    "This type of achievement pressure often makes it difficult to relax.",
    "The mind can become conditioned to expect constant judgment.",
    "When self-criticism persists, it can affect your sleep and appetite.",
    "This kind of perfectionism often creates difficulty with creativity.",
    "The mind can struggle to find joy in activities when focused on performance.",
    "When achievement pressure continues, it can affect your relationships.",
    "This type of fear of failure often makes it difficult to be vulnerable.",
    "The mind can get stuck in loops of constant evaluation.",
    "When perfectionism persists, it can affect your ability to learn.",
    "This type of achievement pressure often makes it difficult to rest.",
    "The mind can become overwhelmed by constant pressure to achieve.",
    "When self-criticism continues, it can affect your overall wellbeing.",
    "This kind of perfectionism often creates difficulty with self-acceptance.",
    "The mind can struggle to find peace when constantly evaluating performance.",
]

PERFORMANCE_INTERVENTIONS = [
    "Right now, lowering perfection expectations might help more than trying to achieve perfect standards. Consider aiming for 'good enough' rather than flawless execution.",
    "It might help to practice self-compassion when perfectionism feels intense. Try treating yourself with the same kindness you would offer a friend.",
    "Creating time limits instead of quality targets could provide some relief. Try setting specific time boundaries for tasks rather than endless refinement.",
    "When achievement pressure feels overwhelming, celebrating small wins might help. Try acknowledging progress rather than focusing only on final outcomes.",
    "Building in 'good enough' standards might help with perfectionism. Try deliberately completing tasks at 80% rather than striving for 100%.",
    "It could help to practice effort-focused evaluation when achievement pressure feels high. Try tracking your effort and process rather than just results.",
    "Creating permission to make mistakes might help with fear of failure. Try viewing errors as learning opportunities rather than failures.",
    "When perfectionism feels intense, having a reality check might help. Try comparing your standards to realistic expectations rather than ideal ones.",
    "Building in self-validation practices might help with achievement pressure. Try acknowledging your own efforts and progress regularly.",
    "It could help to practice progress tracking when perfectionism feels overwhelming. Try focusing on improvement rather than perfection.",
    "Creating boundaries around work might help with achievement pressure. Try setting clear limits on working hours and availability.",
    "When fear of failure persists, it might help to have a failure reframing practice. Try viewing setbacks as data rather than judgments.",
    "Building in collaborative work might help with perfectionism. Try sharing responsibilities and learning from others' approaches.",
    "It could help to practice self-acceptance when achievement pressure feels high. Try accepting yourself as worthy regardless of performance.",
    "Creating structured feedback systems might help with perfectionism. Try seeking balanced feedback rather than self-criticism.",
    "When achievement pressure feels overwhelming, professional support might be beneficial. Consider speaking with a therapist about perfectionism.",
    "Building in play and creativity might help with fear of failure. Try engaging in activities without performance expectations.",
    "It could help to practice values-based decision making when perfectionism feels intense. Try focusing on what matters rather than perfect execution.",
    "Creating celebration rituals might help with achievement pressure. Try acknowledging completion and progress regularly.",
    "When perfectionism persists, it might help to have a perfectionism awareness practice. Try noticing when perfectionism is driving your behavior.",
    "Building in learning-focused mindset might help with fear of failure. Try viewing challenges as opportunities to grow rather than tests of worth.",
    "It could help to practice self-forgiveness when achievement pressure feels high. Try releasing yourself from past perceived failures.",
    "Creating support systems might help with perfectionism. Try surrounding yourself with people who value effort over perfection.",
    "When achievement pressure feels overwhelming, it might help to have a reality check practice. Try comparing your expectations to reasonable standards.",
    "Building in rest and recovery might help with fear of failure. Try scheduling regular breaks without guilt.",
    "It could help to practice authentic self-expression when perfectionism feels intense. Try allowing yourself to be imperfect.",
    "Creating learning opportunities from mistakes might help with achievement pressure. Try analyzing setbacks for insights rather than criticism.",
    "When perfectionism persists, professional support might be beneficial. Consider coaching or therapy for performance anxiety.",
    "Building in community connection might help with fear of failure. Try engaging with others who share similar struggles.",
    "It could help to practice self-worth separation when achievement pressure feels high. Try recognizing that your value isn't tied to performance.",
    "Creating mindful awareness of perfectionism might help. Try noticing when perfectionistic thoughts arise without acting on them.",
    "When achievement pressure feels overwhelming, it might help to have a support network. Try identifying people who encourage growth over perfection.",
]

PERFORMANCE_FOLLOWUPS = [
    "Do you often delay tasks because you feel they must be done perfectly?",
    "How often do you find yourself revising work that's already good enough?",
    "Does it feel difficult to submit or share work that isn't flawless?",
    "Do you notice yourself setting unrealistically high standards?",
    "How does perfectionism affect your ability to start new projects?",
    "Does it feel difficult to celebrate achievements that aren't perfect?",
    "Do you notice yourself comparing your work to others constantly?",
    "How does fear of failure impact your willingness to take risks?",
    "Does it feel difficult to ask for help or admit uncertainty?",
    "Do you notice yourself procrastinating on important tasks?",
    "How does perfectionism affect your relationships with colleagues?",
    "Does it feel difficult to accept constructive feedback?",
    "Do you notice yourself working longer than necessary on tasks?",
    "How does achievement pressure affect your sleep and rest?",
    "Does it feel difficult to delegate tasks to others?",
    "Do you notice yourself constantly seeking approval for your work?",
    "How does perfectionism affect your ability to enjoy hobbies?",
    "Does it feel difficult to try new things without mastering them first?",
    "Do you notice yourself being overly self-critical about mistakes?",
    "How does fear of failure affect your decision-making?",
    "Does it feel difficult to say 'good enough' and move on?",
    "Do you notice yourself avoiding challenges where you might not succeed?",
    "How does perfectionism affect your relationships with family?",
    "Does it feel difficult to accept compliments or praise?",
    "Do you notice yourself constantly checking your work for errors?",
    "How does achievement pressure affect your ability to relax?",
    "Does it feel difficult to collaborate with others on projects?",
    "Do you notice yourself setting impossible deadlines for yourself?",
    "How does perfectionism affect your ability to learn new skills?",
    "Does it feel difficult to share work-in-progress with others?",
    "Do you notice yourself being overly concerned about others' opinions?",
    "How does fear of failure affect your willingness to be vulnerable?",
    "Does it feel difficult to enjoy the process rather than just the outcome?",
    "Do you notice yourself constantly comparing yourself to others?",
    "How does perfectionism affect your ability to ask for help?",
    "Does it feel difficult to accept that mistakes are normal?",
    "Do you notice yourself working excessively to meet your standards?",
    "How does achievement pressure affect your overall wellbeing?",
]


# ============================================
# GENERAL SUPPORT POOLS
# ============================================

GENERAL_INTROS = [
    "Thank you for sharing this honestly.",
    "I'm here to help.",
    "That sounds really challenging.",
    "I understand how difficult that must be.",
    "You're not alone in feeling this way.",
    "That sounds like a lot to handle.",
    "I'm here to listen and support you.",
    "That sounds really stressful.",
    "I understand how overwhelming that can feel.",
    "You deserve support through this.",
    "That sounds like it's weighing on you.",
    "I'm here to help you navigate this.",
    "That sounds emotionally taxing.",
    "I understand how exhausting that can be.",
    "You don't have to face this alone.",
    "That sounds like a heavy burden.",
    "I'm here to support you through this.",
    "That sounds really difficult.",
    "I understand how challenging that must feel.",
    "You deserve care and compassion.",
    "That sounds like it's taking a toll.",
    "I'm here to help you find relief.",
    "That sounds overwhelming.",
    "I understand how heavy that can feel.",
    "You don't have to carry this by yourself.",
    "That sounds emotionally demanding.",
    "I'm here to listen without judgment.",
    "That sounds really hard.",
    "I understand how taxing that can be.",
    "You deserve support and understanding.",
    "That sounds like it's affecting you deeply.",
    "I'm here to help you through this.",
    "That sounds challenging.",
    "I understand how difficult that feels.",
    "You don't have to go through this alone.",
]

GENERAL_OBSERVATIONS = [
    "Your responses suggest you're carrying a significant mental and emotional load.",
    "It sounds like you're experiencing considerable stress and pressure.",
    "Your description indicates you're dealing with multiple challenges.",
    "It seems like you're feeling overwhelmed by various stressors.",
    "Your words suggest you're experiencing significant strain.",
    "It sounds like you're dealing with considerable emotional weight.",
    "Your responses indicate you're facing multiple difficulties.",
    "It seems like you're feeling burdened by various pressures.",
    "Your description suggests you're experiencing significant stress.",
    "It sounds like you're dealing with considerable mental strain.",
    "Your responses indicate you're facing overwhelming challenges.",
    "It seems like you're feeling weighed down by stress.",
    "Your words suggest you're experiencing significant pressure.",
    "It sounds like you're dealing with considerable emotional weight.",
    "Your responses indicate you're facing multiple stressors.",
    "It seems like you're feeling burdened by challenges.",
    "Your description suggests you're experiencing significant strain.",
    "It sounds like you're dealing with considerable mental pressure.",
    "Your responses indicate you're facing overwhelming difficulties.",
    "It seems like you're feeling weighed down by stress.",
    "Your words suggest you're experiencing significant emotional weight.",
    "It sounds like you're dealing with considerable strain.",
    "Your responses indicate you're facing multiple challenges.",
    "It seems like you're feeling burdened by pressures.",
    "Your description suggests you're experiencing significant stress.",
    "It sounds like you're dealing with considerable mental weight.",
    "Your responses indicate you're facing overwhelming stressors.",
    "It seems like you're feeling weighed down by difficulties.",
    "Your words suggest you're experiencing significant pressure.",
    "It sounds like you're dealing with considerable emotional strain.",
    "Your responses indicate you're facing multiple challenges.",
    "It seems like you're feeling burdened by stress.",
    "Your description suggests you're experiencing significant mental pressure.",
    "It sounds like you're dealing with considerable strain.",
    "Your responses indicate you're facing overwhelming difficulties.",
    "It seems like you're feeling weighed down by stress.",
    "Your words suggest you're experiencing significant emotional weight.",
]

GENERAL_REASONING = [
    "When multiple stressors accumulate, it can feel like everything is demanding your attention at once.",
    "This kind of overwhelming pressure often makes it difficult to know where to start or what to prioritize.",
    "The mind can become fatigued when trying to manage numerous challenges simultaneously.",
    "When emotional weight builds up, it can impact your ability to function effectively in daily life.",
    "This type of accumulated stress often makes it harder to find moments of peace or clarity.",
    "The nervous system can become overwhelmed when dealing with multiple persistent stressors.",
    "When mental pressure continues, it can affect your sleep, appetite, and overall wellbeing.",
    "This kind of overwhelming burden often makes it difficult to enjoy life or find pleasure.",
    "The mind can struggle to concentrate when juggling numerous concerns and responsibilities.",
    "When emotional strain persists, it can impact your relationships and social connections.",
    "This type of accumulated stress often makes decision-making feel overwhelming.",
    "The body can manifest physical symptoms when dealing with prolonged mental pressure.",
    "When multiple challenges continue, it can affect your motivation and energy levels.",
    "This kind of overwhelming burden often makes it difficult to see a way forward.",
    "The mind can become stuck in worry loops when dealing with numerous stressors.",
    "When emotional weight builds up, it can affect your self-esteem and confidence.",
    "This type of accumulated stress often makes it hard to ask for help or support.",
    "The nervous system can become dysregulated when experiencing prolonged pressure.",
    "When mental pressure continues, it can impact your ability to work or study effectively.",
    "This kind of overwhelming burden often makes it difficult to maintain routines.",
    "The mind can struggle with emotional regulation when dealing with multiple challenges.",
    "When emotional strain persists, it can affect your physical health and immune system.",
    "This type of accumulated stress often makes it hard to find moments of joy.",
    "The body can experience fatigue when constantly managing mental pressure.",
    "When multiple stressors continue, it can affect your sense of hope and optimism.",
    "This kind of overwhelming burden often makes it difficult to connect with others.",
    "The mind can become overwhelmed and struggle to find solutions.",
    "When emotional weight builds up, it can affect your ability to care for yourself.",
    "This type of accumulated stress often makes decision-making feel paralyzing.",
    "The nervous system can become exhausted when dealing with prolonged pressure.",
    "When mental pressure continues, it can impact your quality of life.",
    "This kind of overwhelming burden often makes it difficult to find relief.",
    "The mind can struggle with perspective when dealing with numerous challenges.",
    "When emotional strain persists, it can affect your overall sense of wellbeing.",
]

GENERAL_INTERVENTIONS = [
    "Instead of trying to solve everything at once, let's identify the biggest source of strain and focus on that first. Consider which area feels most urgent and addressable.",
    "It might help to break down overwhelming challenges into smaller, more manageable pieces. Try identifying one small action you can take today.",
    "Creating structure around self-care could provide some stability. Try establishing basic routines for sleep, meals, and brief moments of rest.",
    "When everything feels overwhelming, having a support system can make a significant difference. Try reaching out to one trusted person for support.",
    "Building in moments of relief might help with accumulated stress. Try scheduling small activities that bring you even brief moments of peace.",
    "It could help to practice self-compassion when dealing with multiple challenges. Try treating yourself with kindness rather than criticism.",
    "Creating boundaries around obligations might help with overwhelming pressure. Try identifying one commitment you can postpone or delegate.",
    "When mental pressure feels intense, professional support might be beneficial. Consider speaking with a therapist or counselor.",
    "Building in physical activity might help with stress accumulation. Try gentle movement like walking or stretching without pressure.",
    "It could help to practice mindfulness when everything feels overwhelming. Try focusing on the present moment rather than worrying about everything.",
    "Creating a priority list might help with multiple stressors. Try identifying the top three concerns that need attention first.",
    "When emotional weight feels heavy, journaling might help. Try writing down your thoughts without judgment or pressure.",
    "Building in social connection might help with accumulated stress. Try scheduling brief interactions with supportive people.",
    "It could help to practice acceptance when dealing with challenges you can't control. Try focusing your energy on what you can influence.",
    "Creating a calming environment might help with overwhelming pressure. Try adjusting your physical space to promote relaxation.",
    "When mental pressure persists, medical evaluation might be appropriate. Consider checking for underlying health conditions.",
    "Building in creative outlets might help with stress accumulation. Try engaging in activities that allow expression without pressure.",
    "It could help to practice gratitude when everything feels overwhelming. Try noticing one small positive thing each day.",
    "Creating structure around problem-solving might help with multiple stressors. Try addressing one challenge at a time.",
    "When emotional weight feels heavy, support groups might help. Try connecting with others who understand similar struggles.",
    "Building in nature exposure might help with accumulated stress. Try spending time outdoors or bringing natural elements indoors.",
    "It could help to practice setting realistic expectations when dealing with multiple challenges. Try adjusting your standards for what's achievable.",
    "Creating a self-care routine might help with overwhelming pressure. Try scheduling regular activities that nurture your wellbeing.",
    "When mental pressure persists, it might help to have a crisis plan. Try identifying emergency resources and support contacts.",
    "Building in moments of joy might help with stress accumulation. Try scheduling small activities that bring you pleasure.",
    "It could help to practice self-validation when dealing with challenges. Try acknowledging the difficulty of your situation.",
    "Creating boundaries around information consumption might help with overwhelming pressure. Try limiting news and social media exposure.",
    "When emotional weight feels heavy, professional support might be beneficial. Consider speaking with a healthcare provider.",
    "Building in relaxation practices might help with accumulated stress. Try deep breathing, meditation, or gentle stretching.",
    "It could help to practice problem-solving when dealing with multiple challenges. Try breaking issues down into smaller, solvable parts.",
    "Creating a support network might help with overwhelming pressure. Try identifying people who can provide different types of support.",
    "When mental pressure persists, it might help to have a routine that includes accomplishment. Try setting small, achievable goals.",
    "Building in sensory pleasure might help with stress accumulation. Try engaging senses through music, aromatherapy, or comfortable textures.",
    "It could help to practice patience when dealing with multiple challenges. Try allowing yourself time to work through difficulties.",
]

GENERAL_FOLLOWUPS = [
    "Would you like to tell me a little more about what's been going on?",
    "How long have you been feeling this way?",
    "Is there anything else on your mind you'd like to share?",
    "What part feels hardest right now?",
    "How is this affecting your daily life?",
    "Have you noticed any changes in your sleep or appetite?",
    "What helps you find even small moments of relief?",
    "Have you talked to anyone else about this?",
    "What does support look like for you right now?",
    "How are you managing with work or study responsibilities?",
    "Have you noticed any patterns in when things feel worse?",
    "What environments tend to make things better or worse?",
    "Have you tried any strategies that have helped?",
    "How are your relationships affected by this?",
    "What does a good day look like for you right now?",
    "Have you noticed any physical symptoms alongside the stress?",
    "What helps you feel even slightly more grounded?",
    "How are you taking care of yourself through this?",
    "Have you considered professional support?",
    "What feels most overwhelming right now?",
    "How is this impacting your ability to enjoy things?",
    "Have you noticed any changes in your energy levels?",
    "What does support from others look like for you?",
    "How are you coping with daily responsibilities?",
    "Have you tried any self-care practices?",
    "What environments help you feel more at ease?",
    "How long have you been dealing with these challenges?",
    "What helps you find even brief moments of peace?",
    "Have you noticed any patterns in your symptoms?",
    "How are your sleep patterns affected?",
    "What does your support system look like?",
    "How are you managing work or study pressures?",
    "Have you tried any stress management techniques?",
    "What helps you feel even slightly better?",
    "How are your relationships with others?",
    "Have you noticed any changes in your appetite?",
    "What environments tend to make things worse?",
    "How long have you been feeling this overwhelmed?",
    "What helps you find even small moments of relief?",
]


# ============================================
# POOL ACCESS HELPERS
# ============================================

def get_response_pools(state: str) -> Dict[str, List[str]]:
    """Return the appropriate response pools for the given emotional state."""
    pools = {
        "high_anxiety": {
            "intros": ANXIETY_INTROS,
            "observations": ANXIETY_OBSERVATIONS,
            "reasoning": ANXIETY_REASONING,
            "interventions": ANXIETY_INTERVENTIONS,
            "followups": ANXIETY_FOLLOWUPS,
        },
        "depressive_fatigue": {
            "intros": DEPRESSION_INTROS,
            "observations": DEPRESSION_OBSERVATIONS,
            "reasoning": DEPRESSION_REASONING,
            "interventions": DEPRESSION_INTERVENTIONS,
            "followups": DEPRESSION_FOLLOWUPS,
        },
        "burnout": {
            "intros": BURNOUT_INTROS,
            "observations": BURNOUT_OBSERVATIONS,
            "reasoning": BURNOUT_REASONING,
            "interventions": BURNOUT_INTERVENTIONS,
            "followups": BURNOUT_FOLLOWUPS,
        },
        "dopamine_overload": {
            "intros": DOPAMINE_INTROS,
            "observations": DOPAMINE_OBSERVATIONS,
            "reasoning": DOPAMINE_REASONING,
            "interventions": DOPAMINE_INTERVENTIONS,
            "followups": DOPAMINE_FOLLOWUPS,
        },
        "performance_pressure": {
            "intros": PERFORMANCE_INTROS,
            "observations": PERFORMANCE_OBSERVATIONS,
            "reasoning": PERFORMANCE_REASONING,
            "interventions": PERFORMANCE_INTERVENTIONS,
            "followups": PERFORMANCE_FOLLOWUPS,
        },
        "general_support": {
            "intros": GENERAL_INTROS,
            "observations": GENERAL_OBSERVATIONS,
            "reasoning": GENERAL_REASONING,
            "interventions": GENERAL_INTERVENTIONS,
            "followups": GENERAL_FOLLOWUPS,
        },
    }
    
    # Handle recurrent states by mapping to base pools
    base_state = state.replace("recurrent_", "")
    return pools.get(base_state, pools["general_support"])


def select_variant(pool: List[str], used: set, max_history: int = 5) -> str:
    """Select a variant from pool avoiding recent repeats."""
    if not pool:
        return "I'm here to support you."
    
    available = [item for item in pool if item not in used]
    if not available:
        # All exhausted, reset and pick randomly
        used.clear()
        available = pool.copy()
    
    if not available:
        # Still empty after reset, return safe fallback
        return "I'm here to help you through this."
    
    return random.choice(available)


def get_state_vocabulary(state: str) -> List[str]:
    """Return state-specific vocabulary for contextual mentions."""
    vocab = {
        "high_anxiety": [
            "racing thoughts", "mental tension", "cognitive overload", "restlessness",
            "uncertainty loops", "hypervigilance", "mental agitation", "cognitive strain",
            "mental hyperactivity", "cognitive tension", "mental stimulation", "cognitive arousal"
        ],
        "depressive_fatigue": [
            "emotional heaviness", "numbness", "disconnection", "motivational depletion",
            "low emotional energy", "emotional exhaustion", "emotional fatigue", "low emotional vitality",
            "emotional disconnection", "motivational fatigue", "emotional depletion", "emotional numbness"
        ],
        "burnout": [
            "sustained exhaustion", "depletion", "overload", "recovery deficit",
            "emotional fatigue", "prolonged exhaustion", "chronic fatigue", "sustained depletion",
            "recovery deficit", "prolonged overload", "chronic exhaustion", "sustained fatigue"
        ],
        "dopamine_overload": [
            "overstimulation", "fragmented attention", "reward cycling", "stimulation fatigue",
            "attention fragmentation", "reward-seeking", "stimulation cycles", "attention deficit",
            "dopamine seeking", "stimulation addiction", "focus fragmentation", "reward loops"
        ],
        "performance_pressure": [
            "self-evaluation", "perfection loops", "fear of underperforming", "achievement pressure",
            "perfectionism", "self-criticism", "performance anxiety", "fear of failure",
            "achievement stress", "perfection anxiety", "performance evaluation", "achievement anxiety"
        ],
        "general_support": [
            "stress", "pressure", "overwhelm", "strain", "burden", "challenges",
            "difficulties", "weight", "mental load", "emotional load", "strain", "pressure"
        ]
    }
    
    base_state = state.replace("recurrent_", "")
    return vocab.get(base_state, vocab["general_support"])
